theme = "slick"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

#[[block]]
#block = "xrandr"
#icons = true
#resolution = true
#interval = 2

[[block]]
block = "music"
buttons = ["play", "next", "prev"]

#[[block]]
#block = "weather"
#format = "{weather} {temp}°, {wind} m/s {direction}"
#service = { name = "openweathermap", api_key = "a4757f9ff1282e97f5fc000adca1d7cd", city_id = "3128760", units = "metric" }

[[block]]
block = "sound"

[[block]]
block = "bluetooth"
mac = "E8:07:BF:03:15:4B"

#[[block]]
#block = "net"
#device = "wlp1s0"
#ssid = true
#speed_up = false
#speed_down = false
#interval = 5

#[[block]]
#block = "net"
#device = "enp0s31f6"
#speed_up = false
#speed_down = false
#interval = 5

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

#[[block]]
#block = "custom"
#interval = 100
#command = "echo  "
#on_click = "powermenu.sh"


